# --- Perusasetukset ---
set -g prefix C-space
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set-option -sg escape-time 10
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -g focus-events on

# --- Näppäinkomennot ---
bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Intuitiivisemmat paneelien jaot (vastaavat Vimiä)
# Uudet paneelit avautuvat samaan kansioon missä olit
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Paneelien koon muuttaminen (Vim-tyyliin, -r mahdollistaa toiston)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# --- Pluginit ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# --- Mukavuusasetukset ---
set -g history-limit 500000
set -g display-time 4000
set -g status-interval 5
set -g @continuum-restore 'on'

# --- Ulkoasu (Everforest-vivahteilla) ---
set -g status-style bg=default
set -g status-left-length 30
set -g status-left "[#S] "
set -g status-right "%H:%M %d-%b-%y"
setw -g window-status-current-style fg='#A7C080',bold # Everforest vihreä (A7C080)
set -g pane-border-style fg='#4b565c'
set -g pane-active-border-style fg='#A7C080'

# Alustetaan TMUX plugin manager (pidä tämä aina viimeisenä)
run '~/.tmux/plugins/tpm/tpm'
